- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/vars.yml
  tasks:
  - name: Ensure a security group for Poker TH servers is in place
    ec2_group:
      name: "{{ ec2_security_group_pokerth }}"
      description: Security Group for Ansible Tower servers
      region: "{{ ec2_region }}"
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 7234
          to_port: 7234
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Provision Poker TH
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      key_name: "{{ec2_key}}"
      region: "{{ ec2_region }}"
      group: "{{ ec2_security_group_pokerth }}"
      instance_type: t2.medium
      image: "{{ ami_id }}"
      wait: true
      exact_count: "1"
      count_tag:
        identity: pokerth
      instance_tags:
        identity: pokerth
    register: pokerth

  - name: Add Poker TH instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=pokerth
    with_items: "{{ pokerth.tagged_instances }}"

- hosts: pokerth
  gather_facts: False
  vars_files:
    - vars/vars.yml
  tasks:
  - name: Install SNAP
    yum:
      name: snapd
      state: present
    become: yes
    
  - name: Stopped firewalld
    service:
      name: firewalld
      state: stopped
    
  - name: Snap install
    snap: 
      name: pokerth
      state: present
    become: yes
    
  - name: Create symlink
    file:
      src: /var/lib/snapd/snap
      dst: /snap
      state: link
    become: yes
